apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
spec:
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      # initContainers:
      # - name: wait-for-mysql
      #   image: busybox:1.35
      #   command:
      #     - sh
      #     - -c
      #     - >
      #       until nslookup mysql-clusterip && mysqladmin ping -h mysql-clusterip --silent; do
      #         echo "Waiting for MySQL";
      #         sleep 5;
      #       done;

      containers:
      - name: dotnet
        image: thitt7/dotnet
        imagePullPolicy: Always
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://+:8001"
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: connection-secret
                key: connectionString
        envFrom:
          - secretRef:
              name: env-secrets
        ports:
        - containerPort: 8001

        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8001
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   failureThreshold: 3
        #   successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-clusterip
spec:
  type: ClusterIP
  selector:
    app: dotnet
  ports:
  - port: 8001
    targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-nodeport
spec:
  type: NodePort
  selector:
    app: dotnet
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30001
