apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
  labels:
    name: ingress-svc
spec:
  ingressClassName: nginx
  tls: 
    - hosts:
      - api.url-tracker.com
      - app.url-tracker.com
      - url-tracker.com
      secretName: url-tracker-tls
  rules:
  - host: api.url-tracker.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dotnet-clusterip
            port: 
              number: 8001

  - host: app.url-tracker.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: next-clusterip
            port: 
              number: 4000

  - host: url-tracker.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: next-clusterip
            port: 
              number: 4000